### ISSUE TITLE
Type naming ideas

### ISSUE THREAD

**Issue by vudaltsov** [php-extended-type-system/type#3]
- `*Type`
- `*T` only for `Bool`, `String`, etc.
- ???

**Comment by klkvsk** [comment]
Recently I was having a similar decision to make, and I come up with the idea of using factory functions. With functions it is possible to use most reserved words, only `array` and `list` are unusable since they are reserved not just for a type, but also a statement. Here is how it looks: https://github.com/klkvsk/dto-generator/blob/main/src/Schema/Types/functions.php

It is intended for using with `use ... as T`, so in a user's project, it will look like: `T\union(T\string(), T\int())`. Personally I find it quite readable and resembling the original lowercase notation for basic types. And as this is just a wrapper, a user still can choose using "*T" classes if they prefer.

**Comment by bridennis** [comment]
Maybe it's worth to think about a prefix again :)
- `As*` for instance `AsBool`, `AsString` etc.

**Comment by vudaltsov** [comment]
@klkvsk , thank you, that sounds interesting. I actually like using functions in my projects, see https://t.me/phpyh/290. I didn't know though that they allow `int`, `string`, etc. names. I will consider this approach.

**Comment by vudaltsov** [comment]
@bridennis, I don't think that `As*` suits. It's a good name for type convertors, but not for types themselves.

**Comment by klimick** [comment]
@vudaltsov what about `const` ?
```php
namespace App
{
    use const Lib\Type\types as t;

    $_list = t->list(t->string);
    /** @psalm-check-type $_list = Lib\TypeDef\Type<list<string>> */

    $_array = t->array(t->int, t->string);
    /** @psalm-check-type $_array = Lib\TypeDef\Type<array<int, string>> */
}
```
https://psalm.dev/r/3203462137

All scalar types are property.
Complex types are methods.
It seems to me this way we can write less parentheses.

**Comment by vudaltsov** [comment]
@klimick, wow! That's a cool technique, never thought of that. I will certainly consider it.

**Comment by vudaltsov** [comment]
I think that for now this issue can be closed. We need to live with `types::` for a while and see, whether it fits. Thank you all for your input!
